### ISSUE TITLE
Cannot build with Typescript "strict" flag set

### ISSUE THREAD

**Issue by grant77** [KostyaTretyak/ng-stack#45]
Steps to reproduce

- Use Angular CLI: 7.3.8
- ng new MyProject
- cd MyProject
- npm i @ng-stack/forms
- add "strict: true" to tsconfig.json
- import NgStackFormsModule in app.module
- ng build

Note:  Everything is ok if you do not set strict to true.

Here is the error:

ERROR in node_modules/@ng-stack/forms/lib/form-builder.d.ts(26,5): error TS2416: Property 'group' in type 'FormBuilder' is not assignable to the same property in base type 'FormBuilder'.
  Type '<T extends object = any, V extends object = ValidatorsModel>(controlsConfig: { [P in keyof T]?: FbControlConfig<T[P], V> | undefined; }, options?: AbstractControlOptions<any> | LegacyControlOptions | null | undefined) => FormGroup<...>' is not assignable to type '(controlsConfig: { [key: string]: any; }, options?: AbstractControlOptions | { [key: string]: any; } | null | undefined) => FormGroup'.
    Type 'FormGroup<{ [x: string]: ...; }, ValidationErrors>' is not assignable to type 'FormGroup'.
      Types of property 'controls' are incompatible.
        Type '{ [x: string]: FormGroup<{}, ValidationErrors> | undefined; }' is not assignable to type '{ [key: string]: AbstractControl; }'.
          Index signatures are incompatible.
            Type 'FormGroup<{}, ValidationErrors> | undefined' is not assignable to type 'AbstractControl'.
              Type 'undefined' is not assignable to type 'AbstractControl'.
node_modules/@ng-stack/forms/lib/form-group.d.ts(5,5): error TS2416: Property 'controls' in type 'FormGroup<T, V>' is not assignable to the same property in base type 'FormGroup'.
  Type '{ [P in keyof T]?: ControlType<T[P], V> | undefined; }' is not assignable to type '{ [key: string]: AbstractControl; }'.
    Type 'ControlType<T[P], V> | undefined' is not assignable to type 'AbstractControl'.
      Type 'undefined' is not assignable to type 'AbstractControl'.

**Comment by Bone008** [comment]
Having the same issue, it seems like the type checker is unhappy about the `controls` property of `FormGroup`. The native version declares it as "`{[key: string]: AbstractControl}`", while this libraries wrapper makes it a partially mapped type. The compiler takes offense to keys now being explicitly allowed the value `undefined`. Not sure if the partial mapping was a conscious API choice.

**Hacky workaround:** Remove the '?' in line 6 of the generated FormGroup typings file:
`node_modules/@ng-stack/forms/lib/form-group.d.ts`

Could probably be fixed in the library source by removing the '?' [in the actual declaration](https://github.com/KostyaTretyak/ng-stack/blob/master/projects/forms/src/lib/form-group.ts#L38), but can't say I understand this library well enough to understand the implications :)
