### ISSUE TITLE
Date should be treated as FormControl, not FormGroup

### ISSUE THREAD

**Issue by grant77** [KostyaTretyak/ng-stack#46]
Type Date should be treated as a FormControl, not a FormGroup.

Ie, I should be able to do this, but it wants establishedDate to be a formGroup:

```
interface Club {
    id: number;
    name: string;
    isPrimary: boolean;
    establishedDate: Date;
}

…

ngOnInit() {
    const { fb } = this;

    fb.group<Club>({
        id: 1,
        name: 'Whatever',
        isPrimary: true,
        establishedDate: new Date(1988, 1, 1)
    });
}
```

**Comment by KostyaTretyak** [comment]
@grant77, try to use `Control` type:

```ts
import { Control } from '@ng-stack/forms';

interface Club {
  id: number;
  name: string;
  isPrimary: boolean;
  establishedDate: Control<Date>;
}
```

**Comment by grant77** [comment]
Yea, I was aware that would work.  I was just thinking that the default for Date should be FormControl being that no one would ever use it otherwise.

**Comment by fongoid** [comment]
~~> @grant77, try to use `Control` type:~~

~~This didn't work for me at all,  with the following errors:~~
```diff
- Type '[Date, UniqToken]' is not assignable to type 'FbControl<Date, ValidatorsModel>'.
-   Type '[Date, UniqToken]' is not assignable to type '[Date, (ValidatorFn<any> | ValidatorFn<any>[] | AbstractControlOptions<any>)?, (AsyncValidatorFn<any> | AsyncValidatorFn<any>[])?]'.
-     Types of property '1' are incompatible.
-       Type 'UniqToken' is not assignable to type 'ValidatorFn<any> | ValidatorFn<any>[] | AbstractControlOptions<any>'.
-         Type 'UniqToken' has no properties in common with type 'AbstractControlOptions<any>'.
```

**Comment by KostyaTretyak** [comment]
@fongoid, can you share, please, more your code?

**Comment by fongoid** [comment]
I think I figured out my error:
Our architecture has a lot of nested components which are all part of a large form. To generate the initial form on parent init, we rely on static methods defined in each component. We pass in initial values of the model to map to the FormGroup. The issue was in reusing the model for parameter and return type. 

Minimal reproduction here: https://stackblitz.com/edit/angular-my7u3f
`StartDate: [initialValue.StartDate],` needs to become `StartDate: [initialValue.StartDate[0]],`
And the populating of the model itself is off (where Date field is now [Date,UniqToken]).

**Comment by KostyaTretyak** [comment]
@grant77, @fongoid, please, checkout `@ng-stack/forms`. In version `1.4.0-beta` I tried to solve the `Control` type problem. So again you can write like this:

```ts
import { Control } from '@ng-stack/forms';

interface Club {
  id: number;
  name: string;
  isPrimary: boolean;
  establishedDate: Control<Date>;
}
```

**Comment by KostyaTretyak** [comment]
You can leave your comments in https://github.com/KostyaTretyak/ng-stack/issues/56
